

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2


remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Test configuration
[profile.default.fuzz]
runs = 256
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["*Test*"]

# RPC endpoints for forking tests (if needed)
[rpc_endpoints]
mainnet = "https://mainnet.base.org"
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"